name: Linux Server

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-linuxserver[0-9]+-TEST[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-linuxserver[0-9]+-RC[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-linuxserver[0-9]+-DC[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-linuxserver[0-9]+"

jobs:
  build_linux_installer:
    runs-on: linux-build-server
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - name: Determine Environment
        id: env
        run: |
          if [[ "${GITHUB_REF}" =~ -TEST[0-9]+$ ]]; then
            echo "env=testing" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" =~ -RC[0-9]+$ ]]; then
            echo "env=staging" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" =~ -DC[0-9]+$ ]]; then
            echo "env=dircon" >> $GITHUB_ENV
          else
            echo "env=production" >> $GITHUB_ENV
          fi

      - name: build praclient
        run: "export PATH=$PATH:/usr/local/go/bin && platforms/linux_server/build_installer.sh ${{ env.env }} ${{ github.ref_name }} ${{ github.sha }}"
